### ISSUE TITLE
Single play not possible with remote system

### ISSUE THREAD

**Issue by carygravel** [Yannik/ansible-role-rsnapshot-backup-host#5]
With a remote system, it is not possible to run the first play without error.

* If you run `rsnapshot-remote-host` first, it fails because the user has not yet been created by `rsnapshot-backup-host`.
* If you run `rsnapshot-backup-host` first, it fails because the user has not yet been created by `rsnapshot-remote-host`.

The best you can do is run `rsnapshot-backup-host`, which creates the user on the host, but errors later fetching the remote user key, then `rsnapshot-remote-host`, which is then successful, and finally `rsnapshot-backup-host` again, which is then successful.

However, my play for `rsnapshot-remote-host` is the trivial:

```
- hosts: REMOTEHOST
  become: true
  roles:
     - role: yannik.rsnapshot-remote-host
       rsnapshot_backup_host: LOCALHOST
```

The above could have been created automatically, given the `backup_host` variable(s) has all the info needed.

Could the two roles not be combined, then it could all be carried out with one play, and without error?
